apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret10
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    component: "{{ .Values.kafka.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
# for getting secret directly from the file
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}

# for hardcoding the secret file data
#stringData:
 # plain-users.json: |
  #  {
   #   "bob": "bob-secret"
   # }
